target := 

relyon := app_gpio.c

compile := sdcc 
#-I/usr/local/freetype/include/freetype2 -L/usr/local/lib -lm

target :$(relyon)
	$(compile) $(relyon) 
clean:
	rm -rf main.asm main.ihx main.lk main.lst main.map main.mem main.rel main.rst main.sym



